-- A little world, made for you — Supabase setup.
--
-- Run once in the Supabase dashboard: SQL Editor → New query → paste → Run.
-- Safe to run again: it only creates what's missing and resets the read rules.
-- Steps and the reasons behind them: supabase.md.

-- 1. Storage ---------------------------------------------------------------
-- One public bucket. The site loads files by their exact URL; with no policy
-- on storage.objects nobody can list what's in it, and nobody can upload
-- except you from the dashboard.
insert into storage.buckets (id, name, public)
values ('birthday-assets', 'birthday-assets', true)
on conflict (id) do update set public = true;

-- 2. Tables -----------------------------------------------------------------
create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  file_path text not null,
  caption text,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.songs (
  id bigint generated by default as identity primary key,
  title text not null,
  artist text,
  file_path text not null,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- 3. Who may read what -------------------------------------------------------
-- The site uses the anon / publishable key, which anyone can see in the page.
-- With row level security on, that key can read active rows and change nothing.
alter table public.photos enable row level security;
alter table public.songs enable row level security;

grant select on public.photos, public.songs to anon;

drop policy if exists "The site reads active photos" on public.photos;
create policy "The site reads active photos" on public.photos
  for select to anon using (active);

drop policy if exists "The site reads active songs" on public.songs;
create policy "The site reads active songs" on public.songs
  for select to anon using (active);

-- 4. Rows ---------------------------------------------------------------------
-- photos.sort_order is the photo's place in the story. Upload the files to
-- these paths, or upload under any name and change file_path to match.
-- Rows for places that already have one are skipped.
insert into public.photos (file_path, sort_order)
select v.file_path, v.sort_order
from (
  values
    ('photos/photo-01.jpg', 1), -- Memories: the larger print
    ('photos/photo-02.jpg', 2), -- Memories: the smaller print
    ('photos/photo-03.jpg', 3), -- Her eyes, seen through water (a close portrait)
    ('photos/photo-04.jpg', 4), -- Her soul: warm light and petals
    ('photos/photo-05.jpg', 5)  -- The birthday: the last one she sees
) as v(file_path, sort_order)
where not exists (select 1 from public.photos p where p.sort_order = v.sort_order)
order by v.sort_order;

-- songs, played in sort_order.
insert into public.songs (title, artist, file_path, sort_order)
select v.title, v.artist, v.file_path, v.sort_order
from (
  values
    ('Perfect', 'Ed Sheeran', 'songs/perfect.mp3', 1),
    ('I Wanna Be Yours', 'Arctic Monkeys', 'songs/i-wanna-be-yours.mp3', 2)
) as v(title, artist, file_path, sort_order)
where not exists (select 1 from public.songs s where s.file_path = v.file_path)
order by v.sort_order;
